a=int(input("enter a:"))
b=int(input("enter b:"))

print("value of a+b:",a+b)
print("value of a-b:",a-b)
print("value of a*b:",a*b)
print("value of a/b:",a/b)
print("value of a^b:",a**b)
print("value of a%b:",a%b)
print("value of a//b:",a//b)